import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function DebateScoreboard({ scores, showDetails = false, }) {
    if (!scores || Object.keys(scores).length === 0) {
        return null;
    }
    // Sort by cumulative score descending
    const sorted = Object.entries(scores).sort((a, b) => b[1].cumulative - a[1].cumulative);
    const leader = sorted[0];
    const maxScore = leader ? leader[1].cumulative : 0;
    return (_jsxs("div", { className: "mb-4 rounded-xl border border-border/50 bg-muted/30 p-4", children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsx("h4", { className: "text-sm font-semibold text-foreground", children: "Debate Scores" }), _jsxs("span", { className: "text-xs text-muted-foreground", children: [sorted.length, " panelist", sorted.length !== 1 ? "s" : ""] })] }), _jsx("div", { className: "space-y-2", children: sorted.map(([name, score], index) => {
                    const isLeader = index === 0 && score.cumulative > 0;
                    const progressPercent = maxScore > 0 ? (score.cumulative / maxScore) * 100 : 0;
                    return (_jsxs("div", { className: "relative", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-6 text-center", children: index === 0 && score.cumulative > 0 ? (_jsx("span", { className: "text-lg", children: "\uD83E\uDD47" })) : index === 1 ? (_jsx("span", { className: "text-lg", children: "\uD83E\uDD48" })) : index === 2 ? (_jsx("span", { className: "text-lg", children: "\uD83E\uDD49" })) : (_jsx("span", { className: "text-sm text-muted-foreground", children: index + 1 })) }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsxs("div", { className: "flex items-center justify-between mb-1", children: [_jsx("span", { className: `text-sm font-medium truncate ${isLeader ? "text-accent" : "text-foreground"}`, children: name }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsxs("span", { className: "text-sm font-semibold text-foreground", children: [score.cumulative, " pts"] }), score.roundDelta !== undefined && score.roundDelta !== 0 && (_jsxs("span", { className: `text-xs font-medium ${score.roundDelta >= 0
                                                                    ? "text-green-500"
                                                                    : "text-red-500"}`, children: [score.roundDelta >= 0 ? "+" : "", score.roundDelta] }))] })] }), _jsx("div", { className: "h-1.5 bg-muted rounded-full overflow-hidden", children: _jsx("div", { className: `h-full rounded-full transition-all duration-500 ${isLeader ? "bg-accent" : "bg-muted-foreground/40"}`, style: { width: `${Math.max(progressPercent, 2)}%` } }) })] })] }), showDetails && score.events && score.events.length > 0 && (_jsx("div", { className: "mt-2 ml-9 space-y-1", children: score.events.slice(-3).map((event, i) => (_jsxs("div", { className: "flex items-center gap-2 text-xs text-muted-foreground", children: [_jsxs("span", { className: `px-1.5 py-0.5 rounded ${event.points >= 0
                                                ? "bg-green-500/10 text-green-600 dark:text-green-400"
                                                : "bg-red-500/10 text-red-600 dark:text-red-400"}`, children: [event.points >= 0 ? "+" : "", event.points] }), _jsx("span", { className: "truncate", children: event.reason })] }, i))) }))] }, name));
                }) }), _jsx("div", { className: "mt-4 pt-3 border-t border-border/30", children: _jsxs("div", { className: "flex flex-wrap gap-3 text-xs text-muted-foreground", children: [_jsxs("span", { children: [_jsx("span", { className: "text-green-500", children: "+10" }), " address claim"] }), _jsxs("span", { children: [_jsx("span", { className: "text-green-500", children: "+8" }), " evidence"] }), _jsxs("span", { children: [_jsx("span", { className: "text-green-500", children: "+24" }), " user upvote"] }), _jsxs("span", { children: [_jsx("span", { className: "text-red-500", children: "-10" }), " ignore claim"] })] }) })] }));
}
export default DebateScoreboard;
