import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { AnimatePresence, motion } from "framer-motion";
import { PROVIDERS, PROVIDER_LABELS } from "../lib/modelProviders";
import { useMemo } from "react";
export function PanelConfigurator({ open, onClose, panelists, onPanelistChange, onAddPanelist, onRemovePanelist, providerKeys, onProviderKeyChange, providerModels, modelStatus, onFetchModels, maxPanelists, }) {
    const canAddMore = panelists.length < maxPanelists;
    const providerSummary = useMemo(() => {
        return panelists.map((panelist) => {
            const providerLabel = PROVIDER_LABELS[panelist.provider];
            const modelLabel = panelist.model || "Select a model";
            return {
                id: panelist.id,
                text: `${panelist.name.trim() || "Panelist"} → ${providerLabel}${panelist.model ? ` (${modelLabel})` : ""}`,
            };
        });
    }, [panelists]);
    return (_jsx(AnimatePresence, { children: open && (_jsxs(motion.div, { className: "fixed inset-0 z-50 flex", initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 }, children: [_jsx("div", { className: "flex-1 bg-slate-950/30 backdrop-blur-sm", onClick: onClose }), _jsxs(motion.div, { initial: { x: 420 }, animate: { x: 0 }, exit: { x: 420 }, transition: { type: "spring", stiffness: 300, damping: 30 }, className: "w-full max-w-xl h-full bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-100 shadow-2xl px-6 py-7 overflow-y-auto", children: [_jsxs("div", { className: "flex items-center justify-between gap-4", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs uppercase tracking-widest text-slate-500 dark:text-slate-400 mb-1", children: "Panel configuration" }), _jsx("h2", { className: "text-2xl font-semibold m-0", children: "LLM panel controls" })] }), _jsx("button", { type: "button", onClick: onClose, className: "rounded-full w-10 h-10 border border-slate-300 dark:border-slate-700 flex items-center justify-center hover:bg-slate-100 dark:hover:bg-slate-800", "aria-label": "Close configuration", children: "\u00D7" })] }), _jsxs("section", { className: "mt-8 space-y-4", children: [_jsxs("header", { children: [_jsx("h3", { className: "text-base font-semibold m-0", children: "Provider API keys" }), _jsx("p", { className: "text-sm text-slate-500 dark:text-slate-400", children: "Keys are stored locally in your browser and only used to fetch model lists." })] }), _jsx("div", { className: "space-y-4", children: PROVIDERS.map((provider) => {
                                        const status = modelStatus[provider.id];
                                        const keyValue = providerKeys[provider.id] ?? "";
                                        return (_jsxs("div", { className: "rounded-2xl border border-slate-200 dark:border-slate-800 p-4 bg-white/70 dark:bg-slate-900/40", children: [_jsxs("div", { className: "flex items-center justify-between gap-3", children: [_jsxs("div", { children: [_jsx("p", { className: "font-semibold m-0", children: provider.label }), _jsx("p", { className: "text-xs text-slate-500 dark:text-slate-400 m-0", children: provider.description })] }), _jsx("a", { href: provider.docs, target: "_blank", rel: "noreferrer", className: "text-xs text-blue-600 dark:text-blue-400", children: "Docs \u2197" })] }), _jsx("label", { className: "mt-3 block text-xs uppercase tracking-wider text-slate-500 dark:text-slate-400", children: "API key" }), _jsxs("div", { className: "mt-1 flex gap-2", children: [_jsx("input", { type: "password", value: keyValue, onChange: (event) => onProviderKeyChange(provider.id, event.target.value), placeholder: provider.keyHint, className: "flex-1 rounded-xl border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2" }), _jsx("button", { type: "button", onClick: () => onFetchModels(provider.id), disabled: !keyValue || status?.loading, className: "rounded-xl border-none bg-slate-900 text-white dark:bg-slate-100 dark:text-slate-900 px-4 py-2 text-sm font-semibold disabled:opacity-60", children: status?.loading ? "Fetching..." : "Fetch" })] }), status?.error && (_jsx("p", { className: "text-sm text-red-600 mt-2", children: status.error }))] }, provider.id));
                                    }) })] }), _jsxs("section", { className: "mt-10", children: [_jsxs("header", { className: "flex flex-wrap items-center justify-between gap-3", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-base font-semibold m-0", children: "Panelists" }), _jsxs("p", { className: "text-sm text-slate-500 dark:text-slate-400", children: ["Configure up to ", maxPanelists, " agents. Currently ", panelists.length, " active."] })] }), _jsx("button", { type: "button", onClick: onAddPanelist, disabled: !canAddMore, className: "rounded-full border border-slate-300 dark:border-slate-700 px-4 py-2 text-sm font-semibold disabled:opacity-60", children: "+ Add panelist" })] }), _jsx("div", { className: "mt-4 space-y-4", children: panelists.map((panelist) => {
                                        const models = providerModels[panelist.provider] ?? [];
                                        const status = modelStatus[panelist.provider];
                                        return (_jsxs("div", { className: "rounded-2xl border border-slate-200 dark:border-slate-800 p-4 bg-white/80 dark:bg-slate-900/40", children: [_jsxs("div", { className: "flex items-center justify-between gap-3", children: [_jsx("input", { value: panelist.name, onChange: (event) => onPanelistChange(panelist.id, { name: event.target.value }), placeholder: "Panelist name", className: "flex-1 rounded-xl border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2 text-base font-semibold" }), _jsx("button", { type: "button", onClick: () => onRemovePanelist(panelist.id), disabled: panelists.length <= 1, className: "text-sm text-red-600 disabled:opacity-40", children: "Remove" })] }), _jsxs("div", { className: "mt-3 grid grid-cols-1 sm:grid-cols-2 gap-3", children: [_jsxs("div", { children: [_jsx("label", { className: "text-xs uppercase tracking-wider text-slate-500 dark:text-slate-400", children: "Provider" }), _jsx("select", { value: panelist.provider, onChange: (event) => onPanelistChange(panelist.id, {
                                                                        provider: event.target.value,
                                                                    }), className: "mt-1 w-full rounded-xl border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2", children: PROVIDERS.map((provider) => (_jsx("option", { value: provider.id, children: provider.label }, provider.id))) })] }), _jsxs("div", { children: [_jsx("label", { className: "text-xs uppercase tracking-wider text-slate-500 dark:text-slate-400", children: "Model" }), _jsxs("div", { className: "mt-1 flex gap-2", children: [_jsxs("select", { value: panelist.model, onChange: (event) => onPanelistChange(panelist.id, {
                                                                                model: event.target.value,
                                                                            }), disabled: models.length === 0, className: "flex-1 rounded-xl border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2", children: [_jsx("option", { value: "", children: models.length === 0 ? "Fetch models" : "Select model" }), models.map((model) => (_jsx("option", { value: model.id, children: model.label }, model.id)))] }), _jsx("button", { type: "button", onClick: () => onFetchModels(panelist.provider), disabled: status?.loading, className: "rounded-xl border border-slate-300 dark:border-slate-700 px-3 py-2 text-xs disabled:opacity-50", children: "Refresh" })] }), status?.error && (_jsxs("p", { className: "text-xs text-red-600 mt-1", children: ["Unable to load models: ", status.error] }))] })] })] }, panelist.id));
                                    }) })] }), _jsxs("section", { className: "mt-10", children: [_jsx("h4", { className: "text-sm font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400", children: "Current plan" }), _jsx("ul", { className: "list-disc pl-5 text-sm text-slate-600 dark:text-slate-400 mt-2 space-y-1", children: providerSummary.map((summary) => (_jsx("li", { children: summary.text }, summary.id))) })] })] })] })) }));
}
