import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { AnimatePresence, motion } from "framer-motion";
import { PROVIDERS, PROVIDER_LABELS } from "../lib/modelProviders";
import { useMemo } from "react";
export function PanelConfigurator({ open, onClose, panelists, onPanelistChange, onAddPanelist, onRemovePanelist, providerKeys, onProviderKeyChange, providerModels, modelStatus, onFetchModels, maxPanelists, }) {
    const canAddMore = panelists.length < maxPanelists;
    const providerSummary = useMemo(() => {
        return panelists.map((panelist) => {
            const providerLabel = PROVIDER_LABELS[panelist.provider];
            const modelLabel = panelist.model || "Select a model";
            return {
                id: panelist.id,
                text: `${panelist.name.trim() || "Panelist"} → ${providerLabel}${panelist.model ? ` (${modelLabel})` : ""}`,
            };
        });
    }, [panelists]);
    return (_jsx(AnimatePresence, { children: open && (_jsxs(motion.div, { className: "fixed inset-0 z-50 flex", initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 }, children: [_jsx("div", { className: "flex-1 bg-foreground/20 backdrop-blur-sm", onClick: onClose }), _jsxs(motion.div, { initial: { x: 420 }, animate: { x: 0 }, exit: { x: 420 }, transition: { type: "spring", stiffness: 280, damping: 28 }, className: "w-full max-w-xl h-full bg-background text-foreground shadow-2xl px-6 py-7 overflow-y-auto border-l border-border", children: [_jsxs("div", { className: "flex items-center justify-between gap-4", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs tracking-wide text-muted-foreground mb-1 font-medium", children: "Configuration" }), _jsx("h2", { className: "text-2xl font-semibold m-0", children: "Panel Settings" })] }), _jsx("button", { type: "button", onClick: onClose, className: "rounded-lg w-10 h-10 border border-border flex items-center justify-center hover:bg-muted transition-colors text-xl", "aria-label": "Close configuration", children: "\u00D7" })] }), _jsxs("section", { className: "mt-8 space-y-4", children: [_jsxs("header", { children: [_jsx("h3", { className: "text-base font-semibold m-0", children: "Provider API Keys" }), _jsx("p", { className: "text-sm text-muted-foreground mt-1", children: "Keys are stored locally in your browser and only used to fetch model lists." })] }), _jsx("div", { className: "space-y-3", children: PROVIDERS.map((provider) => {
                                        const status = modelStatus[provider.id];
                                        const keyValue = providerKeys[provider.id] ?? "";
                                        return (_jsxs("div", { className: "rounded-lg border border-border p-4 bg-card", children: [_jsxs("div", { className: "flex items-center justify-between gap-3", children: [_jsxs("div", { children: [_jsx("p", { className: "font-semibold m-0 text-foreground", children: provider.label }), _jsx("p", { className: "text-xs text-muted-foreground m-0 mt-0.5", children: provider.description })] }), _jsx("a", { href: provider.docs, target: "_blank", rel: "noreferrer", className: "text-xs text-accent hover:opacity-70 transition-opacity", children: "Docs \u2197" })] }), _jsx("label", { className: "mt-3 block text-xs tracking-wide text-muted-foreground font-medium", children: "API Key" }), _jsxs("div", { className: "mt-1.5 flex gap-2", children: [_jsx("input", { type: "password", value: keyValue, onChange: (event) => onProviderKeyChange(provider.id, event.target.value), placeholder: provider.keyHint, className: "flex-1 rounded-lg border border-border bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-accent/50" }), _jsx("button", { type: "button", onClick: () => onFetchModels(provider.id), disabled: !keyValue || status?.loading, className: "rounded-lg border-none bg-foreground text-background px-4 py-2 text-sm font-medium disabled:opacity-50 hover:opacity-90 transition-opacity", children: status?.loading ? "Fetching..." : "Fetch" })] }), status?.error && (_jsx("p", { className: "text-sm text-destructive mt-2", children: status.error }))] }, provider.id));
                                    }) })] }), _jsxs("section", { className: "mt-10", children: [_jsxs("header", { className: "flex flex-wrap items-center justify-between gap-3", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-base font-semibold m-0", children: "Panelists" }), _jsxs("p", { className: "text-sm text-muted-foreground mt-1", children: ["Configure up to ", maxPanelists, " agents. Currently ", panelists.length, " active."] })] }), _jsx("button", { type: "button", onClick: onAddPanelist, disabled: !canAddMore, className: "rounded-lg border border-border px-4 py-2 text-sm font-medium disabled:opacity-50 hover:bg-muted transition-colors", children: "+ Add panelist" })] }), _jsx("div", { className: "mt-4 space-y-3", children: panelists.map((panelist) => {
                                        const models = providerModels[panelist.provider] ?? [];
                                        const status = modelStatus[panelist.provider];
                                        return (_jsxs("div", { className: "rounded-lg border border-border p-4 bg-card", children: [_jsxs("div", { className: "flex items-center justify-between gap-3", children: [_jsx("input", { value: panelist.name, onChange: (event) => onPanelistChange(panelist.id, { name: event.target.value }), placeholder: "Panelist name", className: "flex-1 rounded-lg border border-border bg-background px-3 py-2 text-base font-semibold text-foreground focus:outline-none focus:ring-2 focus:ring-accent/50" }), _jsx("button", { type: "button", onClick: () => onRemovePanelist(panelist.id), disabled: panelists.length <= 1, className: "text-sm text-destructive disabled:opacity-40 hover:opacity-70 transition-opacity", children: "Remove" })] }), _jsxs("div", { className: "mt-3 grid grid-cols-1 sm:grid-cols-2 gap-3", children: [_jsxs("div", { children: [_jsx("label", { className: "text-xs tracking-wide text-muted-foreground font-medium", children: "Provider" }), _jsx("select", { value: panelist.provider, onChange: (event) => onPanelistChange(panelist.id, {
                                                                        provider: event.target.value,
                                                                    }), className: "mt-1.5 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-accent/50", children: PROVIDERS.map((provider) => (_jsx("option", { value: provider.id, children: provider.label }, provider.id))) })] }), _jsxs("div", { children: [_jsx("label", { className: "text-xs tracking-wide text-muted-foreground font-medium", children: "Model" }), _jsxs("div", { className: "mt-1.5 flex gap-2", children: [_jsxs("select", { value: panelist.model, onChange: (event) => onPanelistChange(panelist.id, {
                                                                                model: event.target.value,
                                                                            }), disabled: models.length === 0, className: "flex-1 rounded-lg border border-border bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-accent/50 disabled:opacity-60", children: [_jsx("option", { value: "", children: models.length === 0 ? "Fetch models" : "Select model" }), models.map((model) => (_jsx("option", { value: model.id, children: model.label }, model.id)))] }), _jsx("button", { type: "button", onClick: () => onFetchModels(panelist.provider), disabled: status?.loading, className: "rounded-lg border border-border px-3 py-2 text-xs disabled:opacity-50 hover:bg-muted transition-colors", children: "\u21BB" })] }), status?.error && (_jsxs("p", { className: "text-xs text-destructive mt-1.5", children: ["Unable to load models: ", status.error] }))] })] })] }, panelist.id));
                                    }) })] }), _jsxs("section", { className: "mt-10 pb-4", children: [_jsx("h4", { className: "text-sm font-semibold tracking-wide text-muted-foreground", children: "Active Configuration" }), _jsx("ul", { className: "list-disc pl-5 text-sm text-foreground mt-2 space-y-1", children: providerSummary.map((summary) => (_jsx("li", { children: summary.text }, summary.id))) })] })] })] })) }));
}
