import React, { FormEvent, memo, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";

import { askPanel, askPanelStream, fetchInitialKeys } from "./api";
import { Markdown } from "./components/Markdown";
import { PanelConfigurator } from "./components/PanelConfigurator";
import { DebateViewer } from "./components/DebateViewer";
import { RegenerateModal } from "./components/RegenerateModal";
import { ThemeToggle } from "./components/theme-toggle";
import { fetchModelsForProvider, PROVIDER_LABELS } from "./lib/modelProviders";
import { findBestModelMatch } from "./lib/modelMatcher";
import { generateUniquePanelistName, isAutoGeneratedName } from "./lib/panelistNaming";
import type {
  AskResponse,
  DebateRound,
  LLMProvider,
  PanelistConfigPayload,
  ProviderKeyMap,
  ProviderModelsMap,
  ProviderModelStatusMap,
} from "./types";

const DEFAULT_THREAD_ID = "demo-thread";

type PanelResponses = AskResponse["panel_responses"];
type ConversationMap = Record<string, MessageEntry[]>;
type StoredConversationMap = Record<string, (MessageEntry & { attachments?: string[] })[]>;

interface MessageEntry {
  id: string;
  question: string;
  attachments: string[];
  summary: string;
  panel_responses: PanelResponses;
  panelists: PanelistConfigPayload[]; // Store panelist configs to show model info
  expanded: boolean;
  debate_history?: DebateRound[]; // Debate rounds if debate mode was used
  debate_mode?: boolean; // Whether this exchange used debate mode
  max_debate_rounds?: number; // Max rounds configured for this exchange
  step_review?: boolean; // Whether to show rounds step-by-step
  debate_paused?: boolean; // Whether debate is paused waiting for user to continue
}

const parseJSON = <T,>(value: string | null, fallback: T): T => {
  try {
    return value ? (JSON.parse(value) as T) : fallback;
  } catch {
    return fallback;
  }
};

const MAX_PANELISTS = 6;
const DEFAULT_PANELISTS: PanelistConfigPayload[] = [
  { id: "panelist-1", name: "ChatGPT", provider: "openai", model: "" },
  { id: "panelist-2", name: "ChatGPT 2", provider: "openai", model: "" },
];

const createPanelist = (existingPanelists: PanelistConfigPayload[]): PanelistConfigPayload => ({
  id: `panelist-${Date.now()}-${Math.random().toString(16).slice(2, 7)}`,
  name: "ChatGPT", // Will be updated with unique suffix if needed
  provider: "openai",
  model: "",
});

const MessageBubble = memo(function MessageBubble({
  entry,
  onToggle,
  isLatest = false,
  messageRef,
  loadingStatus = "Panel is thinking...",
  onCopy,
  onDelete,
  onRegenerate,
  onContinueDebate,
}: {
  entry: MessageEntry;
  onToggle: () => void;
  isLatest?: boolean;
  messageRef?: React.RefObject<HTMLDivElement>;
  loadingStatus?: string;
  onCopy?: (text: string) => void;
  onDelete?: () => void;
  onRegenerate?: () => void;
  onContinueDebate?: () => void;
}) {
  const [viewMode, setViewMode] = React.useState<"list" | "grid">("list");

  return (
    <motion.article
      ref={messageRef}
      className="flex flex-col gap-6 min-w-0 group/message"
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
    >
      {/* User message */}
      <div className="flex flex-col items-end self-end text-right gap-2 w-full max-w-[90%] sm:max-w-[85%] md:max-w-[80%]">
        <div className="flex items-center gap-2 w-full justify-end">
          <span className="text-[11px] font-medium tracking-wider uppercase text-muted-foreground/70 px-1">You</span>
          <div className="flex gap-1 opacity-0 group-hover/message:opacity-100 transition-opacity">
            {onCopy && (
              <button
                type="button"
                onClick={() => onCopy(entry.question)}
                className="p-1 rounded hover:bg-muted/40 transition-colors"
                title="Copy question"
              >
                <svg viewBox="0 0 24 24" className="w-3 h-3 text-muted-foreground" fill="none" stroke="currentColor" strokeWidth="2">
                  <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                  <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
                </svg>
              </button>
            )}
          </div>
        </div>
        <motion.div
          className="w-full bg-foreground text-background rounded-2xl px-4 py-3 shadow-sm break-words max-h-[400px] overflow-y-auto prose-sm"
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.4, delay: 0.1, ease: [0.16, 1, 0.3, 1] }}
        >
          <div className="text-sm leading-relaxed">
            <Markdown content={entry.question} />
            {entry.attachments.length > 0 && (
              <div className="mt-4 flex flex-wrap gap-2.5">
                {entry.attachments.map((src, index) => (
                  <motion.img
                    key={index}
                    src={src}
                    alt={`attachment-${index + 1}`}
                    className="w-20 h-20 object-cover rounded-xl border-2 border-background/30 shadow-sm"
                    initial={{ opacity: 0, scale: 0.8 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ duration: 0.3, delay: 0.2 + index * 0.05 }}
                  />
                ))}
              </div>
            )}
          </div>
        </motion.div>
      </div>

      {/* Assistant response */}
      <div className="flex flex-col items-start self-start text-left gap-2 w-full">
        <div className="flex items-center gap-2 w-full flex-wrap">
          <span className="text-[11px] font-medium tracking-wider uppercase text-muted-foreground/70 px-1">Panel</span>

          {/* Mode indicator badge */}
          {entry.summary && (
            <>
              {entry.debate_mode && entry.debate_history && entry.debate_history.length > 0 ? (
                <div className="flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-accent/10 border border-accent/30">
                  <svg viewBox="0 0 24 24" className="w-3 h-3 text-accent" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
                    <path d="M8 10h.01M12 10h.01M16 10h.01" />
                  </svg>
                  <span className="text-[10px] font-semibold text-accent uppercase tracking-wide">
                    Debate Mode
                  </span>
                  <span className="text-[10px] text-accent/70">
                    {entry.debate_history.length} round{entry.debate_history.length !== 1 ? 's' : ''}
                    {entry.debate_history[entry.debate_history.length - 1]?.consensus_reached &&
                      <span className="ml-1">• Consensus ✓</span>
                    }
                  </span>
                </div>
              ) : (
                <div className="flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-muted/30 border border-border/40">
                  <svg viewBox="0 0 24 24" className="w-3 h-3 text-muted-foreground" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z" />
                  </svg>
                  <span className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wide">
                    Quick Response
                  </span>
                </div>
              )}
            </>
          )}

          <div className="flex gap-1 opacity-0 group-hover/message:opacity-100 transition-opacity ml-auto">
            {onCopy && entry.summary && (
              <button
                type="button"
                onClick={() => onCopy(entry.summary)}
                className="p-1 rounded hover:bg-muted/40 transition-colors"
                title="Copy response"
              >
                <svg viewBox="0 0 24 24" className="w-3 h-3 text-muted-foreground" fill="none" stroke="currentColor" strokeWidth="2">
                  <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                  <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
                </svg>
              </button>
            )}
            {onRegenerate && (
              <button
                type="button"
                onClick={onRegenerate}
                className="p-1 rounded hover:bg-muted/40 transition-colors"
                title="Regenerate response"
              >
                <svg viewBox="0 0 24 24" className="w-3 h-3 text-muted-foreground" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M21 2v6h-6M3 12a9 9 0 0 1 15-6.7L21 8M3 22v-6h6m6 0a9 9 0 0 1-15-6.7L3 16" />
                </svg>
              </button>
            )}
            {onDelete && (
              <button
                type="button"
                onClick={onDelete}
                className="p-1 rounded hover:bg-destructive/20 transition-colors"
                title="Delete message"
              >
                <svg viewBox="0 0 24 24" className="w-3 h-3 text-muted-foreground hover:text-destructive" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M3 6h18M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
                </svg>
              </button>
            )}
          </div>
        </div>
        <motion.div
          className="w-full break-words"
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.4, delay: 0.2, ease: [0.16, 1, 0.3, 1] }}
        >
          {entry.summary ? (
            <>
              <div className="prose prose-sm dark:prose-invert max-w-none">
                <Markdown content={entry.summary} />
              </div>

              {entry.debate_mode && entry.debate_history && entry.debate_history.length > 0 ? (
                <DebateViewer
                  debateHistory={entry.debate_history}
                  panelists={entry.panelists}
                  onCopy={onCopy}
                  stepReview={entry.step_review}
                  debatePaused={entry.debate_paused}
                  onContinue={onContinueDebate}
                />
              ) : (
                <>
                <div className="mt-5 flex items-center gap-3">
                  <button
                    type="button"
                    className="inline-flex items-center gap-2 text-[13px] font-medium bg-transparent text-accent/90 border-none p-0 cursor-pointer hover:text-accent transition-colors"
                    onClick={onToggle}
                  >
                    {entry.expanded ? "Hide individual responses" : "Show individual responses"}
                    <svg viewBox="0 0 24 24" aria-hidden="true" className={`w-3.5 h-3.5 transition-transform duration-200 ${entry.expanded ? "rotate-180" : ""}`}>
                      <path fill="currentColor" d="M7 10l5 5 5-5z" />
                    </svg>
                  </button>
                {entry.expanded && Object.keys(entry.panel_responses).length > 1 && (
                  <div className="flex gap-1 border border-border/50 rounded-md p-0.5">
                    <button
                      type="button"
                      onClick={() => setViewMode("list")}
                      className={`px-2 py-1 text-[11px] rounded transition-colors ${
                        viewMode === "list"
                          ? "bg-foreground/10 text-foreground"
                          : "text-muted-foreground hover:text-foreground"
                      }`}
                      title="List view"
                    >
                      <svg viewBox="0 0 24 24" className="w-3.5 h-3.5" fill="none" stroke="currentColor" strokeWidth="2">
                        <line x1="8" y1="6" x2="21" y2="6" />
                        <line x1="8" y1="12" x2="21" y2="12" />
                        <line x1="8" y1="18" x2="21" y2="18" />
                        <line x1="3" y1="6" x2="3.01" y2="6" />
                        <line x1="3" y1="12" x2="3.01" y2="12" />
                        <line x1="3" y1="18" x2="3.01" y2="18" />
                      </svg>
                    </button>
                    <button
                      type="button"
                      onClick={() => setViewMode("grid")}
                      className={`px-2 py-1 text-[11px] rounded transition-colors ${
                        viewMode === "grid"
                          ? "bg-foreground/10 text-foreground"
                          : "text-muted-foreground hover:text-foreground"
                      }`}
                      title="Grid view"
                    >
                      <svg viewBox="0 0 24 24" className="w-3.5 h-3.5" fill="none" stroke="currentColor" strokeWidth="2">
                        <rect x="3" y="3" width="7" height="7" />
                        <rect x="14" y="3" width="7" height="7" />
                        <rect x="14" y="14" width="7" height="7" />
                        <rect x="3" y="14" width="7" height="7" />
                      </svg>
                    </button>
                  </div>
                )}
              </div>
              <AnimatePresence>
                {entry.expanded && (
                  <motion.div
                    className={`mt-6 border-t border-border/50 pt-6 ${
                      viewMode === "grid"
                        ? "grid grid-cols-1 md:grid-cols-2 gap-4"
                        : "flex flex-col gap-4"
                    }`}
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: "auto" }}
                    exit={{ opacity: 0, height: 0 }}
                    transition={{ duration: 0.3, ease: [0.16, 1, 0.3, 1] }}
                  >
                    {Object.entries(entry.panel_responses).map(([name, text], idx) => {
                      // Find the panelist config to show model info
                      const panelist = entry.panelists.find((p) => p.name === name);
                      return (
                      <motion.article
                        key={name}
                        className="border border-border/40 rounded-2xl p-5 bg-muted/20 hover:bg-muted/30 transition-colors group/response"
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.3, delay: idx * 0.05 }}
                      >
                        <div className="flex items-center justify-between gap-3 mb-3">
                          <div className="flex items-center gap-2">
                            <div className="w-8 h-8 rounded-full bg-accent/10 flex items-center justify-center text-accent font-semibold text-xs">
                              {name.charAt(0).toUpperCase()}
                            </div>
                            <div className="flex flex-col">
                              <h4 className="m-0 text-foreground text-[13px] font-semibold tracking-wide">{name}</h4>
                              {panelist && (
                                <span className="text-[10px] text-muted-foreground mt-0.5">
                                  {PROVIDER_LABELS[panelist.provider]} · {panelist.model}
                                </span>
                              )}
                            </div>
                          </div>
                          {onCopy && (
                            <button
                              type="button"
                              onClick={() => onCopy(text)}
                              className="opacity-0 group-hover/response:opacity-100 p-1.5 rounded hover:bg-muted/40 transition-all"
                              title="Copy response"
                            >
                              <svg viewBox="0 0 24 24" className="w-3.5 h-3.5 text-muted-foreground" fill="none" stroke="currentColor" strokeWidth="2">
                                <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                                <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
                              </svg>
                            </button>
                          )}
                        </div>
                        <div className="text-[13px] leading-relaxed text-muted-foreground prose prose-sm dark:prose-invert max-w-none">
                          <Markdown content={text} />
                        </div>
                      </motion.article>
                      );
                    })}
                  </motion.div>
                )}
              </AnimatePresence>
                </>
              )}
            </>
          ) : (
            <div className="flex items-center gap-3">
              <motion.div
                className="flex gap-1.5"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.3 }}
              >
                <motion.div
                  className="w-2 h-2 rounded-full bg-muted-foreground/40"
                  animate={{ scale: [1, 1.2, 1], opacity: [0.4, 0.8, 0.4] }}
                  transition={{ duration: 1.2, repeat: Infinity, delay: 0 }}
                />
                <motion.div
                  className="w-2 h-2 rounded-full bg-muted-foreground/40"
                  animate={{ scale: [1, 1.2, 1], opacity: [0.4, 0.8, 0.4] }}
                  transition={{ duration: 1.2, repeat: Infinity, delay: 0.2 }}
                />
                <motion.div
                  className="w-2 h-2 rounded-full bg-muted-foreground/40"
                  animate={{ scale: [1, 1.2, 1], opacity: [0.4, 0.8, 0.4] }}
                  transition={{ duration: 1.2, repeat: Infinity, delay: 0.4 }}
                />
              </motion.div>
              <span className="text-[13px] text-muted-foreground/60">{loadingStatus}</span>
            </div>
          )}
        </motion.div>
      </div>
    </motion.article>
  );
});
MessageBubble.displayName = "MessageBubble";

export default function App() {
  const [threadId, setThreadId] = useState(() => localStorage.getItem("threadId") ?? DEFAULT_THREAD_ID);
  const [threads, setThreads] = useState<string[]>(() => {
    const stored = parseJSON<string[]>(localStorage.getItem("threads"), []);
    if (!stored.includes(DEFAULT_THREAD_ID)) {
      stored.unshift(DEFAULT_THREAD_ID);
    }
    return Array.from(new Set(stored));
  });
  const [conversations, setConversations] = useState<ConversationMap>(() => {
    const raw = parseJSON<StoredConversationMap>(localStorage.getItem("conversations"), {});
    const normalized: ConversationMap = {};
    Object.entries(raw).forEach(([id, entries]) => {
      normalized[id] = (entries ?? []).map((entry) => ({
        ...entry,
        attachments: entry.attachments ?? [],
        panel_responses: entry.panel_responses ?? {},
        panelists: entry.panelists ?? [], // Fallback for old messages without panelists
        expanded: Boolean(entry.expanded),
      }));
    });
    if (!normalized[DEFAULT_THREAD_ID]) {
      normalized[DEFAULT_THREAD_ID] = [];
    }
    return normalized;
  });
  const [newThreadName, setNewThreadName] = useState("");
  const [isCreatingThread, setIsCreatingThread] = useState(false);
  const [panelists, setPanelists] = useState<PanelistConfigPayload[]>(() => {
    const stored = parseJSON<PanelistConfigPayload[]>(localStorage.getItem("panelists"), DEFAULT_PANELISTS);
    return stored.length > 0 ? stored : DEFAULT_PANELISTS;
  });
  const [providerKeys, setProviderKeys] = useState<ProviderKeyMap>(() =>
    parseJSON<ProviderKeyMap>(localStorage.getItem("providerKeys"), {})
  );
  const [providerModels, setProviderModels] = useState<ProviderModelsMap>(() =>
    parseJSON<ProviderModelsMap>(localStorage.getItem("providerModels"), {})
  );
  const [modelStatus, setModelStatus] = useState<ProviderModelStatusMap>({});
  const [configOpen, setConfigOpen] = useState(false);
  const [showKeyboardShortcuts, setShowKeyboardShortcuts] = useState(false);
  const [regenerateModalOpen, setRegenerateModalOpen] = useState(false);
  const [regenerateIndex, setRegenerateIndex] = useState<number | null>(null);
  const [debateMode, setDebateMode] = useState(() =>
    parseJSON<boolean>(localStorage.getItem("debateMode"), false)
  );
  const [maxDebateRounds, setMaxDebateRounds] = useState(() =>
    parseJSON<number>(localStorage.getItem("maxDebateRounds"), 3)
  );
  const [stepReview, setStepReview] = useState(() =>
    parseJSON<boolean>(localStorage.getItem("stepReview"), false)
  );
  const [loading, setLoading] = useState(false);
  const [loadingStatus, setLoadingStatus] = useState<string>("Panel is thinking...");
  const [error, setError] = useState<string | null>(null);
  const [abortController, setAbortController] = useState<AbortController | null>(null);
  const [showScrollToBottom, setShowScrollToBottom] = useState(false);
  const [sidebarVisible, setSidebarVisible] = useState(() => {
    const stored = localStorage.getItem("sidebarVisible");
    return stored !== null ? stored === "true" : true; // Default to visible
  });
  const [enabledPanelists, setEnabledPanelists] = useState<Set<string>>(() => {
    const stored = localStorage.getItem("enabledPanelists");
    if (stored) {
      try {
        const parsed = JSON.parse(stored);
        return new Set(Array.isArray(parsed) ? parsed : []);
      } catch {
        return new Set();
      }
    }
    // Default: all panelists enabled
    return new Set(panelists.map((p) => p.id));
  });
  const newThreadInputRef = useRef<HTMLInputElement>(null);
  const messageListRef = useRef<HTMLDivElement>(null);
  const latestMessageRef = useRef<HTMLDivElement>(null);

  const messages = conversations[threadId] ?? [];

  // Auto-scroll to latest message when messages change
  useEffect(() => {
    if (latestMessageRef.current && messages.length > 0) {
      // Small delay to allow DOM to update
      setTimeout(() => {
        latestMessageRef.current?.scrollIntoView({
          behavior: "smooth",
          block: "end"
        });
      }, 100);
    }
  }, [messages.length]);

  useEffect(() => {
    localStorage.setItem("threadId", threadId);
  }, [threadId]);

  useEffect(() => {
    localStorage.setItem("threads", JSON.stringify(threads));
  }, [threads]);

  useEffect(() => {
    localStorage.setItem("conversations", JSON.stringify(conversations));
  }, [conversations]);

  useEffect(() => {
    localStorage.setItem("panelists", JSON.stringify(panelists));
  }, [panelists]);

  useEffect(() => {
    localStorage.setItem("providerKeys", JSON.stringify(providerKeys));
  }, [providerKeys]);

  useEffect(() => {
    localStorage.setItem("providerModels", JSON.stringify(providerModels));
  }, [providerModels]);

  useEffect(() => {
    localStorage.setItem("sidebarVisible", String(sidebarVisible));
  }, [sidebarVisible]);

  useEffect(() => {
    localStorage.setItem("enabledPanelists", JSON.stringify(Array.from(enabledPanelists)));
  }, [enabledPanelists]);

  useEffect(() => {
    localStorage.setItem("debateMode", JSON.stringify(debateMode));
  }, [debateMode]);

  useEffect(() => {
    localStorage.setItem("maxDebateRounds", JSON.stringify(maxDebateRounds));
  }, [maxDebateRounds]);

  useEffect(() => {
    localStorage.setItem("stepReview", JSON.stringify(stepReview));
  }, [stepReview]);

  // Sync enabled panelists when panelists change (enable new ones by default)
  useEffect(() => {
    setEnabledPanelists((prev) => {
      const newEnabled = new Set(prev);
      panelists.forEach((p) => {
        if (!newEnabled.has(p.id)) {
          newEnabled.add(p.id);
        }
      });
      // Remove IDs that no longer exist
      const currentIds = new Set(panelists.map((p) => p.id));
      Array.from(newEnabled).forEach((id) => {
        if (!currentIds.has(id)) {
          newEnabled.delete(id);
        }
      });
      return newEnabled;
    });
  }, [panelists]);

  useEffect(() => {
    if (!threads.includes(threadId)) {
      setThreads((prev) => Array.from(new Set([...prev, threadId])));
    }
    if (!conversations[threadId]) {
      setConversations((prev) => ({ ...prev, [threadId]: [] }));
    }
  }, [threadId, threads, conversations]);

  useEffect(() => {
    if (isCreatingThread) {
      const frame = requestAnimationFrame(() => newThreadInputRef.current?.focus());
      return () => cancelAnimationFrame(frame);
    }
  }, [isCreatingThread]);

  // Fetch initial API keys from environment variables on mount
  useEffect(() => {
    async function loadInitialKeys() {
      console.log('[API Keys] Fetching initial keys from backend...');
      const initialKeys = await fetchInitialKeys();
      console.log('[API Keys] Received from backend:', Object.keys(initialKeys).filter(k => initialKeys[k]).join(', ') || 'none');

      // Only populate keys that aren't already set in localStorage
      const storedKeys = parseJSON<ProviderKeyMap>(localStorage.getItem("providerKeys"), {});
      console.log('[API Keys] Stored keys in localStorage:', Object.keys(storedKeys).filter(k => storedKeys[k as LLMProvider]?.trim()).join(', ') || 'none');

      const mergedKeys = { ...storedKeys };
      let keysAdded = 0;

      for (const [provider, key] of Object.entries(initialKeys)) {
        // Only use environment key if no stored key exists
        if (key && !storedKeys[provider as LLMProvider]?.trim()) {
          mergedKeys[provider as LLMProvider] = key;
          keysAdded++;
          console.log(`[API Keys] Added ${provider} key from backend`);
        }
      }

      // Update state if we have new keys
      if (JSON.stringify(mergedKeys) !== JSON.stringify(storedKeys)) {
        console.log(`[API Keys] Updating provider keys (${keysAdded} new keys)`);
        setProviderKeys(mergedKeys);
      } else {
        console.log('[API Keys] No new keys to add');
      }
    }

    loadInitialKeys();
  }, []); // Run only once on mount

  // Keyboard shortcuts
  useEffect(() => {
    function handleKeyboardShortcut(e: KeyboardEvent) {
      const isMac = navigator.platform.toUpperCase().indexOf('MAC') >= 0;
      const modKey = isMac ? e.metaKey : e.ctrlKey;

      // Cmd/Ctrl + N: New thread
      if (modKey && e.key === 'n') {
        e.preventDefault();
        setIsCreatingThread(true);
        setNewThreadName("");
      }

      // Cmd/Ctrl + /: Toggle settings
      if (modKey && e.key === '/') {
        e.preventDefault();
        setConfigOpen((prev) => !prev);
      }

      // Esc: Close modals
      if (e.key === 'Escape') {
        if (showKeyboardShortcuts) {
          e.preventDefault();
          setShowKeyboardShortcuts(false);
        }
        if (configOpen) {
          e.preventDefault();
          setConfigOpen(false);
        }
        if (isCreatingThread) {
          e.preventDefault();
          cancelThreadCreation();
        }
      }
    }

    window.addEventListener('keydown', handleKeyboardShortcut);
    return () => window.removeEventListener('keydown', handleKeyboardShortcut);
  }, [configOpen, isCreatingThread, showKeyboardShortcuts]);

  const togglePanelist = useCallback((id: string) => {
    setEnabledPanelists((prev) => {
      const newSet = new Set(prev);
      if (newSet.has(id)) {
        // Don't allow disabling the last panelist
        if (newSet.size <= 1) {
          return prev;
        }
        newSet.delete(id);
      } else {
        newSet.add(id);
      }
      return newSet;
    });
  }, []);

  const preparedPanelists = useMemo(
    () =>
      panelists
        .filter((panelist) => enabledPanelists.has(panelist.id))
        .map((panelist, index) => ({
          ...panelist,
          name: panelist.name.trim() || `Panelist ${index + 1}`,
        })),
    [panelists, enabledPanelists]
  );

  const panelistSummaries = useMemo(
    () =>
      panelists.map((panelist, index) => ({
        id: panelist.id,
        name: panelist.name.trim() || `Panelist ${index + 1}`,
        provider: PROVIDER_LABELS[panelist.provider],
        model: panelist.model,
        enabled: enabledPanelists.has(panelist.id),
      })),
    [panelists, enabledPanelists]
  );

  const sanitizedProviderKeys = useMemo(() => {
    const entries = Object.entries(providerKeys).filter(([, value]) => Boolean(value?.trim()));
    return Object.fromEntries(entries.map(([key, value]) => [key, value.trim()])) as ProviderKeyMap;
  }, [providerKeys]);

  const handleSend = useCallback(
    async ({
      question,
      attachments,
      customDebateMode,
      customMaxRounds,
      customStepReview,
    }: {
      question: string;
      attachments: string[];
      customDebateMode?: boolean;
      customMaxRounds?: number;
      customStepReview?: boolean;
    }) => {
      const hasContent = Boolean(question.trim()) || attachments.length > 0;
      if (!hasContent || loading) {
        return;
      }

      setLoading(true);
      setError(null);

      // Create abort controller for this request
      const controller = new AbortController();
      setAbortController(controller);

      const sanitizedQuestion = question.trim() || "See attached images.";
      const entryId = `${threadId}-${Date.now()}`;

      // Use custom debate settings if provided, otherwise use global settings
      const useDebateMode = customDebateMode !== undefined ? customDebateMode : debateMode;
      const useMaxRounds = customMaxRounds !== undefined ? customMaxRounds : maxDebateRounds;
      const useStepReview = customStepReview !== undefined ? customStepReview : stepReview;

      // Immediately add user message with loading state for assistant response
      const optimisticEntry: MessageEntry = {
        id: entryId,
        question: sanitizedQuestion,
        attachments,
        summary: "", // Will be filled when response arrives
        panel_responses: {},
        panelists: panelists, // Store panelist configs to show model info later
        expanded: false,
        debate_mode: useDebateMode,
        max_debate_rounds: useMaxRounds,
        step_review: useStepReview,
        debate_history: [],
      };

      setConversations((prev) => ({
        ...prev,
        [threadId]: [...(prev[threadId] ?? []), optimisticEntry],
      }));

      try {
        await askPanelStream(
          {
            thread_id: threadId.trim(),
            question: sanitizedQuestion,
            attachments,
            panelists: preparedPanelists,
            provider_keys: sanitizedProviderKeys,
            debate_mode: useDebateMode,
            max_debate_rounds: useMaxRounds,
            step_review: useStepReview,
          },
          {
            onStatus: (message) => {
              setLoadingStatus(message);
            },
            onDebateRound: (round) => {
              // Update the entry with the new debate round in real-time
              setConversations((prev) => ({
                ...prev,
                [threadId]: prev[threadId]?.map((entry) =>
                  entry.id === entryId
                    ? {
                        ...entry,
                        debate_history: [...(entry.debate_history || []), round],
                      }
                    : entry
                ) ?? [],
              }));
            },
            onDebatePaused: (result) => {
              // Debate paused for user review
              setConversations((prev) => ({
                ...prev,
                [threadId]: prev[threadId]?.map((entry) =>
                  entry.id === entryId
                    ? {
                        ...entry,
                        panel_responses: result.panel_responses || entry.panel_responses,
                        debate_history: entry.debate_history,
                        debate_paused: true,
                      }
                    : entry
                ) ?? [],
              }));
              // Clear loading state when debate pauses
              setLoading(false);
              setLoadingStatus("Panel is thinking...");
            },
            onResult: (result) => {
              // Update the entry with the actual response
              setConversations((prev) => ({
                ...prev,
                [threadId]: prev[threadId]?.map((entry) =>
                  entry.id === entryId
                    ? {
                        ...entry,
                        summary: result.summary,
                        panel_responses: result.panel_responses,
                        // Keep accumulated debate history from streaming (onDebateRound)
                        debate_history: entry.debate_history,
                        debate_paused: false,
                      }
                    : entry
                ) ?? [],
              }));
            },
            onError: (err) => {
              // Remove the optimistic entry on error
              setConversations((prev) => ({
                ...prev,
                [threadId]: prev[threadId]?.filter((entry) => entry.id !== entryId) ?? [],
              }));
              setError(err.message);
              setLoading(false);
              setLoadingStatus("Panel is thinking..."); // Reset status
            },
          },
          controller.signal
        );
      } catch (err) {
        // Don't show error if request was aborted by user, but still clean up
        if (err instanceof Error && err.name === 'AbortError') {
          console.log('Request aborted by user');
          // Remove the optimistic entry when aborted
          setConversations((prev) => ({
            ...prev,
            [threadId]: prev[threadId]?.filter((entry) => entry.id !== entryId) ?? [],
          }));
          return;
        }

        // Remove the optimistic entry on error
        setConversations((prev) => ({
          ...prev,
          [threadId]: prev[threadId]?.filter((entry) => entry.id !== entryId) ?? [],
        }));
        setError(err instanceof Error ? err.message : "Something went wrong");
        throw err;
      } finally {
        setLoading(false);
        setLoadingStatus("Panel is thinking..."); // Reset status
        setAbortController(null); // Clean up abort controller
      }
    },
    [loading, preparedPanelists, sanitizedProviderKeys, threadId, debateMode, maxDebateRounds, stepReview]
  );

  const handleContinueDebate = useCallback(
    async (entryId: string) => {
      const entry = conversations[threadId]?.find((e) => e.id === entryId);
      if (!entry || !entry.debate_paused) {
        return;
      }

      setLoading(true);
      setError(null);

      // Create abort controller for this request
      const controller = new AbortController();
      setAbortController(controller);

      try {
        await askPanelStream(
          {
            thread_id: threadId.trim(),
            question: "", // Not needed for continuation
            attachments: [],
            panelists: preparedPanelists,
            provider_keys: sanitizedProviderKeys,
            continue_debate: true, // Signal this is a continuation
          },
          {
            onStatus: (message) => {
              setLoadingStatus(message);
            },
            onDebateRound: (round) => {
              // Add the new debate round
              setConversations((prev) => ({
                ...prev,
                [threadId]: prev[threadId]?.map((e) =>
                  e.id === entryId
                    ? {
                        ...e,
                        debate_history: [...(e.debate_history || []), round],
                      }
                    : e
                ) ?? [],
              }));
            },
            onDebatePaused: (result) => {
              // Still paused - waiting for next round
              setConversations((prev) => ({
                ...prev,
                [threadId]: prev[threadId]?.map((e) =>
                  e.id === entryId
                    ? {
                        ...e,
                        panel_responses: result.panel_responses || e.panel_responses,
                        debate_paused: true,
                      }
                    : e
                ) ?? [],
              }));
              // Clear loading state when debate pauses
              setLoading(false);
              setLoadingStatus("Panel is thinking...");
            },
            onResult: (result) => {
              // Debate complete - got final summary
              setConversations((prev) => ({
                ...prev,
                [threadId]: prev[threadId]?.map((e) =>
                  e.id === entryId
                    ? {
                        ...e,
                        summary: result.summary,
                        panel_responses: result.panel_responses,
                        debate_paused: false,
                      }
                    : e
                ) ?? [],
              }));
            },
            onError: (err) => {
              setError(err.message);
              setLoading(false);
              setLoadingStatus("Panel is thinking...");
            },
          },
          controller.signal
        );
      } catch (err) {
        // Don't show error if request was aborted by user
        if (err instanceof Error && err.name === 'AbortError') {
          console.log('Request aborted by user');
          return;
        }
        setError(err instanceof Error ? err.message : "Something went wrong");
      } finally {
        setLoading(false);
        setLoadingStatus("Panel is thinking...");
        setAbortController(null); // Clean up abort controller
      }
    },
    [conversations, threadId, preparedPanelists, sanitizedProviderKeys]
  );

  const stopGeneration = useCallback(() => {
    if (abortController) {
      console.log('Stopping generation...');
      abortController.abort();
      setAbortController(null);
      setLoading(false);
      setLoadingStatus("Panel is thinking...");
    }
  }, [abortController]);

  const handleScrollToBottom = useCallback(() => {
    const el = messageListRef.current;
    if (!el) return;
    el.scrollTo({ top: el.scrollHeight, behavior: "smooth" });
    setShowScrollToBottom(false);
  }, []);

  // Track scroll position for showing/hiding scroll button
  useEffect(() => {
    function handleScroll() {
      const el = messageListRef.current;
      if (!el) return;
      const distanceFromBottom = el.scrollHeight - el.scrollTop - el.clientHeight;
      setShowScrollToBottom(distanceFromBottom > 300);
    }

    handleScroll();
    const el = messageListRef.current;
    if (!el) return;
    el.addEventListener("scroll", handleScroll);
    return () => el.removeEventListener("scroll", handleScroll);
  }, []);

  function toggleEntry(index: number) {
    setConversations((prev) => ({
      ...prev,
      [threadId]: prev[threadId]?.map((item, i) =>
        i === index ? { ...item, expanded: !item.expanded } : item
      ) ?? [],
    }));
  }

  function handleThreadSelect(id: string) {
    setThreadId(id);
  }

  function handleRenameThread(id: string) {
    const proposed = prompt("Rename thread", id)?.trim();
    if (!proposed || proposed === id || threads.includes(proposed)) {
      return;
    }

    setThreads((prev) => prev.map((thread) => (thread === id ? proposed : thread)));
    setConversations((prev) => {
      const { [id]: entries, ...rest } = prev;
      return { ...rest, [proposed]: entries ?? [] };
    });
    if (threadId === id) {
      setThreadId(proposed);
    }
  }

  function handleDeleteThread(id: string) {
    if (threads.length === 1) {
      return;
    }
    setThreads((prev) => prev.filter((thread) => thread !== id));
    setConversations((prev) => {
      const { [id]: _removed, ...rest } = prev;
      return rest;
    });

    if (threadId === id) {
      const fallback = threads.find((thread) => thread !== id) ?? DEFAULT_THREAD_ID;
      setThreadId(fallback);
    }
  }

  function handleCreateThread(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const trimmed = newThreadName.trim();
    if (!trimmed) return;

    setThreads((prev) => (prev.includes(trimmed) ? prev : [...prev, trimmed]));
    setConversations((prev) => (prev[trimmed] ? prev : { ...prev, [trimmed]: [] }));
    setThreadId(trimmed);
    setNewThreadName("");
    setIsCreatingThread(false);
  }

  function cancelThreadCreation() {
    setIsCreatingThread(false);
    setNewThreadName("");
  }

  function handleThreadInputKeyDown(event: React.KeyboardEvent<HTMLInputElement>) {
    if (event.key === "Escape") {
      event.preventDefault();
      cancelThreadCreation();
    }
  }

  const handleAddPanelist = useCallback(() => {
    setPanelists((prev) => {
      if (prev.length >= MAX_PANELISTS) return prev;
      const base = createPanelist(prev);
      const defaultModel = providerModels[base.provider]?.[0]?.id ?? "";
      const uniqueName = generateUniquePanelistName(base.provider, defaultModel, prev);
      return [...prev, { ...base, model: defaultModel, name: uniqueName }];
    });
  }, [providerModels]);

  const handleRemovePanelist = useCallback((id: string) => {
    setPanelists((prev) => {
      if (prev.length <= 1) {
        return prev;
      }
      const filtered = prev.filter((panelist) => panelist.id !== id);
      return filtered.length > 0 ? filtered : prev;
    });
  }, []);

  const handleProviderKeyChange = useCallback((provider: LLMProvider, key: string) => {
    setProviderKeys((prev) => ({ ...prev, [provider]: key }));
  }, []);

  const handleFetchProviderModels = useCallback(
    async (provider: LLMProvider) => {
      const apiKey = providerKeys[provider]?.trim();
      if (!apiKey) {
        setModelStatus((prev) => ({
          ...prev,
          [provider]: { loading: false, error: "API key required" },
        }));
        return;
      }

      setModelStatus((prev) => ({
        ...prev,
        [provider]: { loading: true, error: null },
      }));

      try {
        const models = await fetchModelsForProvider(provider, apiKey);
        setProviderModels((prev) => ({ ...prev, [provider]: models }));
        setModelStatus((prev) => ({
          ...prev,
          [provider]: { loading: false, error: null },
        }));
        setPanelists((prev) => {
          const updated = prev.map((panelist) => {
            if (panelist.provider !== provider) return panelist;
            if (!models.length) {
              return { ...panelist, model: "" };
            }

            let nextModel = panelist.model;
            let shouldUpdateName = false;

            // If panelist has no model, set to first available
            if (!panelist.model) {
              nextModel = models[0].id;
              shouldUpdateName = true;
            } else {
              // Try to find best match for the current model
              const bestMatch = findBestModelMatch(panelist.model, models);

              if (bestMatch && bestMatch.id !== panelist.model) {
                // Found a different match - use it
                nextModel = bestMatch.id;
                shouldUpdateName = true;
              }
            }

            // Auto-update name if model changed and name is auto-generated
            let nextName = panelist.name;
            if (shouldUpdateName && isAutoGeneratedName(panelist.name, panelist.provider, panelist.model)) {
              nextName = generateUniquePanelistName(panelist.provider, nextModel, prev, panelist.id);
            }

            return { ...panelist, model: nextModel, name: nextName };
          });

          return updated;
        });
      } catch (err) {
        setModelStatus((prev) => ({
          ...prev,
          [provider]: {
            loading: false,
            error: err instanceof Error ? err.message : "Failed to fetch models",
          },
        }));
      }
    },
    [providerKeys]
  );

  const handlePanelistChange = useCallback(
    (id: string, updates: Partial<PanelistConfigPayload>) => {
      setPanelists((prev) =>
        prev.map((panelist) => {
          if (panelist.id !== id) return panelist;
          const nextProvider = updates.provider ?? panelist.provider;
          const providerModelsList = providerModels[nextProvider] ?? [];
          let nextModel = updates.model ?? panelist.model;

          // Track if provider changed
          const providerChanged = updates.provider && updates.provider !== panelist.provider;

          if (providerChanged) {
            nextModel = providerModelsList[0]?.id ?? "";

            // Auto-fetch models if provider changed and we have an API key
            const hasKey = providerKeys[nextProvider]?.trim();
            const hasModels = (providerModels[nextProvider]?.length ?? 0) > 0;

            if (hasKey && !hasModels) {
              // Fetch models asynchronously without blocking the UI
              handleFetchProviderModels(nextProvider).catch((err) => {
                console.error(`Failed to auto-fetch models for ${nextProvider}:`, err);
              });
            }
          }

          // Auto-generate name if model/provider changed and current name is auto-generated
          let nextName = updates.name ?? panelist.name;
          const modelChanged = updates.model !== undefined && updates.model !== panelist.model;

          if ((modelChanged || providerChanged) && !updates.name) {
            // Check if current name is auto-generated (using OLD provider to check)
            const wasAutoGenerated = isAutoGeneratedName(panelist.name, panelist.provider, panelist.model);

            if (wasAutoGenerated) {
              // Auto-update name to match new provider/model
              nextName = generateUniquePanelistName(nextProvider, nextModel, prev, id);
            }
          }

          return {
            ...panelist,
            ...updates,
            provider: nextProvider,
            model: nextModel,
            name: nextName,
          };
        })
      );
    },
    [providerModels, providerKeys, handleFetchProviderModels]
  );

  const handleLoadPreset = useCallback(
    async (preset: import("./lib/presetManager").PanelistPreset) => {
      // Regenerate names based on current naming logic to ensure consistency
      const panelistsWithUpdatedNames = preset.panelists.map((panelist, index, arr) => {
        const uniqueName = generateUniquePanelistName(
          panelist.provider,
          panelist.model,
          arr.slice(0, index), // Only consider panelists before this one
          panelist.id
        );
        return { ...panelist, name: uniqueName };
      });

      // Set panelists with regenerated names
      setPanelists(panelistsWithUpdatedNames);

      // Auto-fetch models for providers used in the preset
      const providersUsed = new Set(preset.panelists.map((p) => p.provider));

      for (const provider of providersUsed) {
        // Fetch models if we have an API key
        const hasKey = providerKeys[provider]?.trim();

        if (hasKey) {
          // Always fetch models when loading preset to ensure proper matching
          // This triggers the smart model matching in handleFetchProviderModels
          handleFetchProviderModels(provider).catch((err) => {
            console.error(`Failed to auto-fetch models for ${provider}:`, err);
          });
        }
      }
    },
    [providerKeys, handleFetchProviderModels]
  );

  // Export/Import functions
  const exportThreadAsJSON = useCallback((threadId: string) => {
    const threadData = {
      threadId,
      messages: conversations[threadId] || [],
      exportedAt: new Date().toISOString(),
    };
    const blob = new Blob([JSON.stringify(threadData, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${threadId}-${new Date().toISOString().split("T")[0]}.json`;
    a.click();
    URL.revokeObjectURL(url);
  }, [conversations]);

  const exportThreadAsMarkdown = useCallback((threadId: string) => {
    const messages = conversations[threadId] || [];
    let markdown = `# ${threadId}\n\n`;
    markdown += `*Exported: ${new Date().toLocaleString()}*\n\n---\n\n`;

    messages.forEach((entry, index) => {
      markdown += `## Exchange ${index + 1}\n\n`;
      markdown += `**You:**\n${entry.question}\n\n`;

      if (entry.attachments.length > 0) {
        markdown += `*Attachments: ${entry.attachments.length} image(s)*\n\n`;
      }

      markdown += `**Panel Summary:**\n${entry.summary}\n\n`;

      if (Object.keys(entry.panel_responses).length > 0) {
        markdown += `### Individual Responses\n\n`;
        Object.entries(entry.panel_responses).forEach(([name, response]) => {
          markdown += `**${name}:**\n${response}\n\n`;
        });
      }

      markdown += `---\n\n`;
    });

    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${threadId}-${new Date().toISOString().split("T")[0]}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }, [conversations]);

  const importThread = useCallback((file: File) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const data = JSON.parse(e.target?.result as string);
        if (!data.threadId || !Array.isArray(data.messages)) {
          throw new Error("Invalid file format");
        }

        const newThreadId = data.threadId;
        let finalThreadId = newThreadId;
        let counter = 1;

        // Avoid overwriting existing threads
        while (threads.includes(finalThreadId)) {
          finalThreadId = `${newThreadId} (${counter})`;
          counter++;
        }

        setThreads((prev) => [...prev, finalThreadId]);
        setConversations((prev) => ({
          ...prev,
          [finalThreadId]: data.messages,
        }));
        setThreadId(finalThreadId);
      } catch (err) {
        setError("Failed to import conversation. Invalid file format.");
      }
    };
    reader.readAsText(file);
  }, [threads]);

  // Message management functions
  const copyToClipboard = useCallback((text: string) => {
    navigator.clipboard.writeText(text).then(() => {
      // Could add a toast notification here
    }).catch((err) => {
      console.error("Failed to copy:", err);
    });
  }, []);

  const deleteMessage = useCallback((index: number) => {
    setConversations((prev) => ({
      ...prev,
      [threadId]: prev[threadId]?.filter((_, i) => i !== index) ?? [],
    }));
  }, [threadId]);

  const openRegenerateModal = useCallback((index: number) => {
    setRegenerateIndex(index);
    setRegenerateModalOpen(true);
  }, []);

  const confirmRegenerate = useCallback(async (useDebateMode: boolean, rounds: number, useStepReview: boolean) => {
    if (regenerateIndex === null) return;

    const entry = conversations[threadId]?.[regenerateIndex];
    if (!entry) return;

    // Remove the old entry
    setConversations((prev) => ({
      ...prev,
      [threadId]: prev[threadId]?.filter((_, i) => i !== regenerateIndex) ?? [],
    }));

    // Re-send the question with custom debate settings
    await handleSend({
      question: entry.question,
      attachments: entry.attachments,
      customDebateMode: useDebateMode,
      customMaxRounds: rounds,
      customStepReview: useStepReview,
    });

    setRegenerateIndex(null);
  }, [regenerateIndex, threadId, conversations, handleSend]);

  return (
    <div className="flex h-screen w-full overflow-hidden bg-background">
      {sidebarVisible && (
        <aside className="hidden lg:flex w-72 flex-shrink-0 bg-card px-6 py-8 flex-col gap-6 border-r border-border/60 relative">
        <div className="flex items-center justify-between gap-3">
          <h2 className="text-lg font-semibold m-0 text-foreground tracking-tight">Conversations</h2>
          <div className="flex items-center gap-2">
            <button
              type="button"
              className="w-8 h-8 rounded-lg border border-border/60 bg-muted/30 text-foreground text-lg font-semibold leading-none flex items-center justify-center cursor-pointer hover:bg-muted hover:border-accent/50 transition-all"
              onClick={() => {
                setIsCreatingThread(true);
                setNewThreadName("");
              }}
              aria-label="Create new thread"
            >
              +
            </button>
            <button
              type="button"
              onClick={() => setSidebarVisible(false)}
              className="w-8 h-8 rounded-lg border border-border/60 text-muted-foreground hover:text-foreground hover:bg-muted/40 hover:border-accent/50 transition-all flex items-center justify-center"
              aria-label="Hide sidebar"
              title="Hide sidebar"
            >
              <svg viewBox="0 0 24 24" className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M21 3H3v18h18V3z" />
                <path d="M10 3v18" />
                <path d="M4 14l3-3-3-3" />
              </svg>
            </button>
          </div>
        </div>
        <ul className="list-none p-0 m-0 flex flex-col gap-1.5 overflow-y-auto flex-1">
          {threads.map((id) => (
            <li key={id} className="group">
              <div className="flex items-center gap-1.5 relative">
                <button
                  type="button"
                  className={`flex-1 flex items-center justify-between px-3.5 py-2 rounded-lg border text-[13px] transition-all ${
                    threadId === id
                      ? "border-accent/60 bg-accent/8 text-accent font-medium"
                      : "border-border/40 bg-transparent font-normal text-foreground hover:bg-muted/30 hover:border-border"
                  }`}
                  onClick={() => handleThreadSelect(id)}
                >
                  <span className="truncate">{id}</span>
                </button>

                {/* Action buttons - visible on hover */}
                <div className="flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity duration-200">
                  <button
                    type="button"
                    onClick={() => exportThreadAsMarkdown(id)}
                    aria-label="Export as Markdown"
                    title="Export as Markdown"
                    className="border-none bg-muted/40 hover:bg-muted cursor-pointer p-1.5 rounded-md transition-colors"
                  >
                    <svg viewBox="0 0 24 24" className="w-3.5 h-3.5 text-foreground/70" fill="none" stroke="currentColor" strokeWidth="2">
                      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                      <polyline points="7 10 12 15 17 10" />
                      <line x1="12" y1="15" x2="12" y2="3" />
                    </svg>
                  </button>
                  <button
                    type="button"
                    onClick={() => handleRenameThread(id)}
                    aria-label="Rename thread"
                    className="border-none bg-muted/40 hover:bg-muted cursor-pointer p-1.5 rounded-md transition-colors"
                  >
                    <svg viewBox="0 0 24 24" className="w-3.5 h-3.5 text-foreground/70" fill="none" stroke="currentColor" strokeWidth="2">
                      <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
                      <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" />
                    </svg>
                  </button>
                  <button
                    type="button"
                    onClick={() => handleDeleteThread(id)}
                    aria-label="Delete thread"
                    className="border-none bg-muted/40 hover:bg-destructive/10 cursor-pointer p-1.5 rounded-md transition-colors group/delete"
                  >
                    <svg viewBox="0 0 24 24" className="w-3.5 h-3.5 text-foreground/70 group-hover/delete:text-destructive transition-colors" fill="none" stroke="currentColor" strokeWidth="2">
                      <path d="M3 6h18" />
                      <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6" />
                      <path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
                      <line x1="10" y1="11" x2="10" y2="17" />
                      <line x1="14" y1="11" x2="14" y2="17" />
                    </svg>
                  </button>
                </div>
              </div>
            </li>
          ))}
        </ul>
        {isCreatingThread && (
          <form className="flex gap-2" onSubmit={handleCreateThread}>
            <input
              ref={newThreadInputRef}
              value={newThreadName}
              onChange={(e) => setNewThreadName(e.target.value)}
              onBlur={() => {
                if (!newThreadName.trim()) {
                  cancelThreadCreation();
                }
              }}
              onKeyDown={handleThreadInputKeyDown}
              placeholder="Name your thread"
              className="flex-1 rounded-lg border border-border/60 px-3 py-2 text-sm font-inherit bg-card text-foreground focus:outline-none focus:ring-2 focus:ring-accent/40 focus:border-accent/60 transition-all"
            />
          </form>
        )}

        {/* Settings and Theme toggle at bottom */}
        <div className="flex flex-col gap-2 pt-4 border-t border-border/40 mt-auto">
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={() => setConfigOpen(true)}
              className="flex-1 flex items-center justify-center gap-2 rounded-lg border border-border/60 px-4 py-2.5 text-[13px] font-medium text-foreground hover:bg-muted/40 hover:border-accent/50 transition-all"
            >
              <svg viewBox="0 0 24 24" className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2">
                <circle cx="12" cy="12" r="3" />
                <path d="M12 1v6m0 6v6m5.2-13l-1 1.7M7.8 19.3l-1-1.7m0-11.6l1 1.7m4.2 9.3l1 1.7M1 12h6m6 0h6" />
              </svg>
              Settings
            </button>
            <ThemeToggle />
          </div>
          <button
            type="button"
            onClick={() => document.getElementById("import-file-input")?.click()}
            className="flex items-center justify-center gap-2 rounded-lg border border-border/60 px-4 py-2.5 text-[13px] font-medium text-foreground hover:bg-muted/40 hover:border-accent/50 transition-all"
          >
            <svg viewBox="0 0 24 24" className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
              <polyline points="17 8 12 3 7 8" />
              <line x1="12" y1="3" x2="12" y2="15" />
            </svg>
            Import Thread
          </button>
          <input
            id="import-file-input"
            type="file"
            accept=".json"
            className="hidden"
            onChange={(e) => {
              const file = e.target.files?.[0];
              if (file) {
                importThread(file);
                e.target.value = ""; // Reset input
              }
            }}
          />
          <button
            type="button"
            onClick={() => setShowKeyboardShortcuts(true)}
            className="flex items-center justify-center gap-2 rounded-lg border border-border/60 px-4 py-2.5 text-[13px] font-medium text-foreground hover:bg-muted/40 hover:border-accent/50 transition-all"
            title="Keyboard Shortcuts"
          >
            <svg viewBox="0 0 24 24" className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2">
              <rect x="2" y="4" width="20" height="16" rx="2" />
              <path d="M6 8h.01M10 8h.01M14 8h.01M18 8h.01M8 12h.01M12 12h.01M16 12h.01M7 16h10" />
            </svg>
            Keyboard Shortcuts
          </button>
        </div>
      </aside>
      )}

      {/* Floating button to show sidebar when hidden */}
      {!sidebarVisible && (
        <button
          type="button"
          onClick={() => setSidebarVisible(true)}
          className="hidden lg:flex fixed left-4 top-6 z-50 w-10 h-10 items-center justify-center rounded-lg bg-card border border-border/60 text-muted-foreground hover:text-foreground hover:bg-muted/40 hover:border-accent/50 transition-all shadow-lg"
          aria-label="Show sidebar"
          title="Show sidebar"
        >
          <svg viewBox="0 0 24 24" className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M3 3h18v18H3V3z" />
            <path d="M10 3v18" />
            <path d="M14 8l3 3-3 3" />
          </svg>
        </button>
      )}

      <main className="flex-1 overflow-hidden bg-transparent flex flex-col">
        {/* Header and panelist info - constrained */}
        <div className="mx-auto w-full max-w-4xl px-4 md:px-6 lg:px-8 py-6 flex flex-col gap-5">
          <header className="flex flex-col gap-2">
            <div className="min-w-0">
              <p className="m-0 text-[11px] text-muted-foreground/70 tracking-wider uppercase font-medium">Thread</p>
              <h1 className="mt-0.5 mb-0 text-2xl font-semibold text-foreground truncate tracking-tight">{threadId}</h1>
            </div>
          </header>

          <div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
            {panelistSummaries.map((summary) => (
              <button
                key={summary.id}
                type="button"
                onClick={() => togglePanelist(summary.id)}
                className={`inline-flex items-center gap-1.5 rounded-lg border px-3 py-1.5 transition-all cursor-pointer ${
                  summary.enabled
                    ? "border-border/40 bg-card/50 hover:bg-card hover:border-accent/40"
                    : "border-border/20 bg-muted/20 opacity-50 hover:opacity-70"
                }`}
                title={summary.enabled ? "Click to disable" : "Click to enable"}
              >
                <span className={`font-semibold text-[12px] ${summary.enabled ? "text-foreground" : "text-muted-foreground"}`}>
                  {summary.name}
                </span>
                <span className="text-muted-foreground text-[11px]">
                  · {summary.provider}
                  {summary.model ? ` · ${summary.model}` : ""}
                </span>
                {summary.enabled && (
                  <svg viewBox="0 0 24 24" className="w-3 h-3 text-accent" fill="currentColor">
                    <circle cx="12" cy="12" r="4" />
                  </svg>
                )}
              </button>
            ))}
          </div>
        </div>

        {/* Chat section - full width with scrollbar at browser edge */}
        <section className="flex flex-1 min-h-0 flex-col relative">
            {/* Scrollable messages area */}
            <div className="flex-1 overflow-y-auto scroll-smooth" ref={messageListRef}>
              <div className="flex flex-col gap-10 py-10 pb-8 mx-auto w-full max-w-3xl px-4 sm:px-6">
                {messages.length === 0 && (
                  <div className="flex-1 flex items-center justify-center">
                    <p className="text-muted-foreground/60 text-center text-sm">Start a conversation by asking a question below.</p>
                  </div>
                )}
                {messages.map((entry, index) => (
                  <MessageBubble
                    key={entry.id}
                    entry={entry}
                    onToggle={() => toggleEntry(index)}
                    isLatest={index === messages.length - 1}
                    messageRef={index === messages.length - 1 ? latestMessageRef : undefined}
                    loadingStatus={loadingStatus}
                    onCopy={copyToClipboard}
                    onDelete={() => deleteMessage(index)}
                    onRegenerate={() => openRegenerateModal(index)}
                    onContinueDebate={() => handleContinueDebate(entry.id)}
                  />
                ))}
              </div>
            </div>

            {/* Gradient fade for smooth transition to composer */}
            <div className="absolute bottom-0 left-0 right-0 h-32 bg-gradient-to-t from-background via-background/80 to-transparent pointer-events-none z-[5]" />

            {/* Scroll button positioned relative to content width */}
            <div className="absolute bottom-0 left-0 right-0 pointer-events-none z-[15]">
              <div className="mx-auto w-full max-w-3xl px-4 sm:px-6 relative">
                <AnimatePresence>
                  {showScrollToBottom && (
                    <motion.button
                      type="button"
                      className="absolute right-0 bottom-[210px] md:bottom-[220px] rounded-full bg-foreground/90 text-background pl-4 pr-5 py-2.5 shadow-lg text-[13px] font-medium hover:bg-foreground transition-all backdrop-blur-sm flex items-center gap-2 pointer-events-auto"
                      onClick={handleScrollToBottom}
                      initial={{ opacity: 0, y: 10, scale: 0.9 }}
                      animate={{ opacity: 1, y: 0, scale: 1 }}
                      exit={{ opacity: 0, y: 10, scale: 0.9 }}
                      transition={{ duration: 0.2 }}
                    >
                      <svg viewBox="0 0 24 24" className="w-4 h-4" fill="currentColor">
                        <path d="M12 16l-6-6h12z"/>
                      </svg>
                      Jump to latest
                    </motion.button>
                  )}
                </AnimatePresence>
              </div>
            </div>

            {/* Fixed composer area at bottom */}
            <div className="pt-8 pb-5 relative z-10 mx-auto w-full max-w-3xl px-4 sm:px-6">
              <ChatComposer
                loading={loading}
                error={error}
                onSend={handleSend}
                onStop={stopGeneration}
                onClearError={() => setError(null)}
                onError={(message) => setError(message)}
              />
            </div>
          </section>
      </main>
      <PanelConfigurator
        open={configOpen}
        onClose={() => setConfigOpen(false)}
        panelists={panelists}
        onPanelistChange={handlePanelistChange}
        onAddPanelist={handleAddPanelist}
        onRemovePanelist={handleRemovePanelist}
        providerKeys={providerKeys}
        onProviderKeyChange={handleProviderKeyChange}
        providerModels={providerModels}
        modelStatus={modelStatus}
        onFetchModels={handleFetchProviderModels}
        maxPanelists={MAX_PANELISTS}
        onLoadPreset={handleLoadPreset}
        debateMode={debateMode}
        onDebateModeChange={setDebateMode}
        maxDebateRounds={maxDebateRounds}
        onMaxDebateRoundsChange={setMaxDebateRounds}
        stepReview={stepReview}
        onStepReviewChange={setStepReview}
      />

      {/* Regenerate Modal */}
      <RegenerateModal
        open={regenerateModalOpen}
        onClose={() => {
          setRegenerateModalOpen(false);
          setRegenerateIndex(null);
        }}
        onConfirm={confirmRegenerate}
        defaultDebateMode={
          regenerateIndex !== null
            ? conversations[threadId]?.[regenerateIndex]?.debate_mode ?? debateMode
            : debateMode
        }
        defaultMaxRounds={
          regenerateIndex !== null
            ? conversations[threadId]?.[regenerateIndex]?.max_debate_rounds ?? maxDebateRounds
            : maxDebateRounds
        }
        defaultStepReview={
          regenerateIndex !== null
            ? conversations[threadId]?.[regenerateIndex]?.step_review ?? stepReview
            : stepReview
        }
      />

      {/* Keyboard Shortcuts Help Modal */}
      <AnimatePresence>
        {showKeyboardShortcuts && (
          <motion.div
            className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/20 backdrop-blur-sm p-4"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={() => setShowKeyboardShortcuts(false)}
          >
            <motion.div
              className="bg-background text-foreground rounded-2xl shadow-2xl max-w-md w-full p-6 border border-border"
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              transition={{ type: "spring", stiffness: 300, damping: 30 }}
              onClick={(e) => e.stopPropagation()}
            >
              <div className="flex items-center justify-between mb-6">
                <h2 className="text-xl font-semibold m-0">Keyboard Shortcuts</h2>
                <button
                  type="button"
                  onClick={() => setShowKeyboardShortcuts(false)}
                  className="rounded-lg w-8 h-8 border border-border flex items-center justify-center hover:bg-muted transition-colors text-lg"
                  aria-label="Close"
                >
                  ×
                </button>
              </div>

              <div className="space-y-4">
                <div className="flex items-center justify-between py-2 border-b border-border/40">
                  <span className="text-sm text-muted-foreground">New thread</span>
                  <kbd className="px-2 py-1 text-xs font-semibold bg-muted rounded border border-border">
                    {navigator.platform.toUpperCase().indexOf('MAC') >= 0 ? '⌘' : 'Ctrl'} + N
                  </kbd>
                </div>

                <div className="flex items-center justify-between py-2 border-b border-border/40">
                  <span className="text-sm text-muted-foreground">Toggle settings</span>
                  <kbd className="px-2 py-1 text-xs font-semibold bg-muted rounded border border-border">
                    {navigator.platform.toUpperCase().indexOf('MAC') >= 0 ? '⌘' : 'Ctrl'} + /
                  </kbd>
                </div>

                <div className="flex items-center justify-between py-2 border-b border-border/40">
                  <span className="text-sm text-muted-foreground">Submit message</span>
                  <kbd className="px-2 py-1 text-xs font-semibold bg-muted rounded border border-border">
                    {navigator.platform.toUpperCase().indexOf('MAC') >= 0 ? '⌘' : 'Ctrl'} + Enter
                  </kbd>
                </div>

                <div className="flex items-center justify-between py-2">
                  <span className="text-sm text-muted-foreground">Close modals</span>
                  <kbd className="px-2 py-1 text-xs font-semibold bg-muted rounded border border-border">
                    Esc
                  </kbd>
                </div>
              </div>

              <div className="mt-6 pt-4 border-t border-border/40">
                <p className="text-xs text-muted-foreground text-center">
                  Press <kbd className="px-1.5 py-0.5 text-xs font-semibold bg-muted rounded border border-border">?</kbd> anytime to show this help
                </p>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

interface ChatComposerProps {
  loading: boolean;
  error: string | null;
  onSend: (payload: { question: string; attachments: string[] }) => Promise<void>;
  onStop: () => void;
  onClearError: () => void;
  onError: (message: string) => void;
}

function ChatComposer({ loading, error, onSend, onStop, onClearError, onError }: ChatComposerProps) {
  const [question, setQuestion] = useState("");
  const [attachments, setAttachments] = useState<string[]>([]);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const hasContent = Boolean(question.trim()) || attachments.length > 0;
  const canSubmit = hasContent && !loading;
  const canStop = loading;

  // Auto-resize textarea based on content
  useEffect(() => {
    const textarea = textareaRef.current;
    if (!textarea) return;

    // Reset height to get accurate scrollHeight
    textarea.style.height = 'auto';

    // Set height based on content, with max limit
    const maxHeight = 120; // ~5 lines max
    const newHeight = Math.min(textarea.scrollHeight, maxHeight);
    textarea.style.height = `${newHeight}px`;

    // Only show scrollbar when content exceeds max height
    textarea.style.overflowY = textarea.scrollHeight > maxHeight ? 'auto' : 'hidden';
  }, [question]);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!canSubmit) return;

    // Clear immediately for better UX
    const currentQuestion = question;
    const currentAttachments = [...attachments];
    setQuestion("");
    setAttachments([]);

    // Refocus textarea
    textareaRef.current?.focus();

    try {
      await onSend({ question: currentQuestion, attachments: currentAttachments });
    } catch {
      // On error, restore the content
      setQuestion(currentQuestion);
      setAttachments(currentAttachments);
    }
  }

  function handleFilesSelected(files: FileList | null) {
    if (!files) return;
    const toRead = Array.from(files).slice(0, 4);
    Promise.all(
      toRead.map(
        (file) =>
          new Promise<string>((resolve, reject) => {
            const reader = new FileReader();
            reader.onload = () => resolve(String(reader.result));
            reader.onerror = reject;
            reader.readAsDataURL(file);
          })
      )
    )
      .then((data) => {
        setAttachments((prev) => [...prev, ...data]);
        if (error) onClearError();
      })
      .catch(() => onError("Failed to load image"));
  }

  function removeAttachment(index: number) {
    setAttachments((prev) => prev.filter((_, i) => i !== index));
  }

  return (
    <form className="min-w-0" onSubmit={handleSubmit}>
      <div className="flex flex-col gap-3 min-w-0">
        <div className="relative rounded-2xl border border-border/50 bg-background/95 backdrop-blur-sm max-w-full shadow-sm">
          <textarea
            ref={textareaRef}
            value={question}
            onChange={(event) => {
              setQuestion(event.target.value);
              if (error) onClearError();
            }}
            onKeyDown={(event) => {
              const isMac = navigator.platform.toUpperCase().indexOf('MAC') >= 0;
              const modKey = isMac ? event.metaKey : event.ctrlKey;

              // Cmd/Ctrl + Enter: Submit
              if (modKey && event.key === 'Enter' && canSubmit) {
                event.preventDefault();
                handleSubmit(event as any);
              }
            }}
            placeholder="Send a message..."
            rows={1}
            className="w-full border-none rounded-2xl px-4 md:px-5 pt-3.5 md:pt-4 pb-14 md:pb-16 text-sm md:text-[15px] font-inherit resize-none overflow-y-hidden bg-transparent text-foreground placeholder:text-muted-foreground/50 focus:outline-none leading-relaxed"
          />

          {/* Button container with separator */}
          <div className="absolute left-0 right-0 bottom-0 pt-3 px-4 md:px-5 pb-3.5 md:pb-4 bg-gradient-to-t from-background/95 via-background/80 to-transparent border-t border-border/20 rounded-b-2xl">
            <div className="flex items-center gap-2 md:gap-2.5">
              <button
                type="button"
                className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg border border-border/50 bg-background/90 text-foreground text-xs font-medium cursor-pointer hover:bg-muted/60 hover:border-border transition-all shadow-sm"
                onClick={() => fileInputRef.current?.click()}
              >
                <svg viewBox="0 0 24 24" aria-hidden="true" className="w-3.5 h-3.5">
                  <path
                    fill="currentColor"
                    d="M16.5 6.5v9.25a4.25 4.25 0 0 1-8.5 0V5a2.75 2.75 0 0 1 5.5 0v9a1.25 1.25 0 0 1-2.5 0V6.5h-1.5V14a2.75 2.75 0 1 0 5.5 0V5a4.25 4.25 0 0 0-8.5 0v10.75a5.75 5.75 0 1 0 11.5 0V6.5z"
                  />
                </svg>
                <span className="hidden sm:inline">Attach</span>
              </button>
              <input
                ref={fileInputRef}
                type="file"
                accept="image/*"
                multiple
                hidden
                onChange={(event) => {
                  handleFilesSelected(event.target.files);
                  event.target.value = "";
                }}
              />
              <motion.button
                type={canStop ? "button" : "submit"}
                onClick={canStop ? (e) => { e.preventDefault(); onStop(); } : undefined}
                className={`ml-auto w-10 h-10 md:w-11 md:h-11 rounded-xl inline-flex items-center justify-center border-none cursor-pointer transition-all shadow-sm disabled:opacity-40 disabled:cursor-not-allowed ${
                  canStop
                    ? 'bg-destructive text-destructive-foreground hover:bg-destructive/90'
                    : 'bg-accent text-accent-foreground hover:opacity-90'
                }`}
                disabled={!canSubmit && !canStop}
                aria-label={canStop ? "Stop generation" : "Send message"}
                whileHover={{ scale: (canSubmit || canStop) ? 1.05 : 1 }}
                whileTap={{ scale: (canSubmit || canStop) ? 0.95 : 1 }}
                animate={{
                  opacity: (hasContent || canStop) ? 1 : 0.3,
                  scale: (hasContent || canStop) ? 1 : 0.9
                }}
                transition={{ duration: 0.2 }}
              >
                {canStop ? (
                  <svg viewBox="0 0 24 24" className="w-5 h-5" fill="currentColor">
                    <rect x="6" y="6" width="12" height="12" rx="1" />
                  </svg>
                ) : (
                  <svg viewBox="0 0 24 24" aria-hidden="true" className="w-5 h-5">
                    <path fill="currentColor" d="M2.01 21 23 12 2.01 3 2 10l15 2-15 2z" />
                  </svg>
                )}
              </motion.button>
            </div>
          </div>
        </div>

        <AnimatePresence>
          {attachments.length > 0 && (
            <motion.div
              className="flex flex-wrap gap-2.5"
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: "auto" }}
              exit={{ opacity: 0, height: 0 }}
            >
              {attachments.map((src, index) => (
                <motion.div
                  key={index}
                  className="relative w-20 h-20 rounded-xl overflow-hidden border-2 border-border/40 shadow-sm group"
                  initial={{ opacity: 0, scale: 0.8 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.8 }}
                  transition={{ duration: 0.2, delay: index * 0.03 }}
                >
                  <img src={src} alt={`preview-${index + 1}`} className="w-full h-full object-cover" />
                  <button
                    type="button"
                    onClick={() => {
                      removeAttachment(index);
                      if (error) onClearError();
                    }}
                    className="absolute top-1 right-1 border-none rounded-full w-6 h-6 text-xs bg-foreground/90 text-background cursor-pointer hover:bg-foreground transition-all opacity-0 group-hover:opacity-100 flex items-center justify-center font-semibold shadow-sm"
                  >
                    ×
                  </button>
                </motion.div>
              ))}
            </motion.div>
          )}
        </AnimatePresence>

        <AnimatePresence>
          {error && (
            <motion.p
              className="text-destructive text-[13px] m-0 px-1"
              initial={{ opacity: 0, y: -5 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -5 }}
            >
              {error}
            </motion.p>
          )}
        </AnimatePresence>
      </div>
    </form>
  );
}
