import type { LLMProvider, PanelistConfigPayload } from "../types";

/**
 * Get brand name for provider
 * Examples:
 * - "openai" → "ChatGPT"
 * - "claude" → "Claude"
 * - "gemini" → "Gemini"
 * - "grok" → "Grok"
 */
export function getProviderBrandName(provider: LLMProvider): string {
  const brandNames: Record<LLMProvider, string> = {
    openai: "ChatGPT",
    claude: "Claude",
    gemini: "Gemini",
    grok: "Grok",
  };
  return brandNames[provider];
}

/**
 * Generate a unique panelist name based on provider
 * Handles duplicates by adding number suffixes (e.g., "ChatGPT 2", "Claude 3")
 */
export function generateUniquePanelistName(
  provider: LLMProvider,
  modelId: string,
  existingPanelists: PanelistConfigPayload[],
  currentPanelistId?: string
): string {
  const baseName = getProviderBrandName(provider);

  // Count how many panelists from this provider already exist (excluding current)
  const sameProviderCount = existingPanelists.filter(
    (p) => p.id !== currentPanelistId && p.provider === provider
  ).length;

  // If this is the first from this provider, use base name without number
  if (sameProviderCount === 0) {
    return baseName;
  }

  // Otherwise add number suffix
  return `${baseName} ${sameProviderCount + 1}`;
}

/**
 * Check if a name appears to be auto-generated (not manually edited)
 * This helps determine if we should auto-update the name when model changes
 */
export function isAutoGeneratedName(name: string, provider: LLMProvider, modelId: string): boolean {
  if (!name) return false;

  const brandName = getProviderBrandName(provider);

  // Check if it matches exactly (e.g., "ChatGPT")
  if (name === brandName) return true;

  // Check if it matches with number suffix (e.g., "ChatGPT 2", "Claude 3")
  const suffixPattern = new RegExp(`^${brandName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')} \\d+$`);
  return suffixPattern.test(name);
}
