import type { LLMProvider, PanelistConfigPayload } from "../types";
/**
 * Extract a friendly short name from a model ID
 * Examples:
 * - "gpt-4o" → "GPT-4o"
 * - "gpt-4o-mini" → "GPT-4o Mini"
 * - "claude-3-5-sonnet-20241022" → "Claude Sonnet"
 * - "gemini-1.5-flash" → "Gemini Flash"
 * - "grok-2-1212" → "Grok 2"
 */
export declare function generateFriendlyModelName(provider: LLMProvider, modelId: string): string;
/**
 * Generate a unique panelist name based on provider and model
 * Handles duplicates by adding number suffixes (e.g., "GPT-4o 2")
 */
export declare function generateUniquePanelistName(provider: LLMProvider, modelId: string, existingPanelists: PanelistConfigPayload[], currentPanelistId?: string): string;
/**
 * Check if a name appears to be auto-generated (not manually edited)
 * This helps determine if we should auto-update the name when model changes
 */
export declare function isAutoGeneratedName(name: string, provider: LLMProvider, modelId: string): boolean;
