import type { LLMProvider, PanelistConfigPayload } from "../types";
/**
 * Get brand name for provider
 * Examples:
 * - "openai" → "ChatGPT"
 * - "claude" → "Claude"
 * - "gemini" → "Gemini"
 * - "grok" → "Grok"
 */
export declare function getProviderBrandName(provider: LLMProvider): string;
/**
 * Generate a unique panelist name based on provider
 * Handles duplicates by adding number suffixes (e.g., "ChatGPT 2", "Claude 3")
 */
export declare function generateUniquePanelistName(provider: LLMProvider, modelId: string, existingPanelists: PanelistConfigPayload[], currentPanelistId?: string): string;
/**
 * Check if a name appears to be auto-generated (not manually edited)
 * This helps determine if we should auto-update the name when model changes
 */
export declare function isAutoGeneratedName(name: string, provider: LLMProvider, modelId: string): boolean;
