import type { LLMProvider, PanelistConfigPayload } from "../types";
/**
 * Get brand name for provider
 * Examples:
 * - "openai" → "ChatGPT"
 * - "claude" → "Claude"
 * - "gemini" → "Gemini"
 * - "grok" → "Grok"
 */
export declare function getProviderBrandName(provider: LLMProvider): string;
/**
 * Generate a unique panelist name based on provider
 * Handles duplicates by adding number suffixes with underscores (e.g., "ChatGPT_2", "Claude_3")
 * No spaces to ensure tagging works properly with @mentions
 */
export declare function generateUniquePanelistName(provider: LLMProvider, modelId: string, existingPanelists: PanelistConfigPayload[], currentPanelistId?: string): string;
/**
 * Check if a name appears to be auto-generated (not manually edited)
 * This helps determine if we should auto-update the name when model changes
 */
export declare function isAutoGeneratedName(name: string, provider: LLMProvider, modelId: string): boolean;
/**
 * Validate panelist name format
 * Names must not contain spaces to allow proper @mention tagging
 * Returns error message if invalid, null if valid
 */
export declare function validatePanelistName(name: string): string | null;
