/**
 * Get brand name for provider
 * Examples:
 * - "openai" → "ChatGPT"
 * - "claude" → "Claude"
 * - "gemini" → "Gemini"
 * - "grok" → "Grok"
 */
export function getProviderBrandName(provider) {
    const brandNames = {
        openai: "ChatGPT",
        claude: "Claude",
        gemini: "Gemini",
        grok: "Grok",
    };
    return brandNames[provider];
}
/**
 * Generate a unique panelist name based on provider
 * Handles duplicates by adding number suffixes with underscores (e.g., "ChatGPT_2", "Claude_3")
 * No spaces to ensure tagging works properly with @mentions
 */
export function generateUniquePanelistName(provider, modelId, existingPanelists, currentPanelistId) {
    const baseName = getProviderBrandName(provider);
    // Count how many panelists from this provider already exist (excluding current)
    const sameProviderCount = existingPanelists.filter((p) => p.id !== currentPanelistId && p.provider === provider).length;
    // If this is the first from this provider, use base name without number
    if (sameProviderCount === 0) {
        return baseName;
    }
    // Otherwise add number suffix with underscore (no spaces for tagging)
    return `${baseName}_${sameProviderCount + 1}`;
}
/**
 * Check if a name appears to be auto-generated (not manually edited)
 * This helps determine if we should auto-update the name when model changes
 */
export function isAutoGeneratedName(name, provider, modelId) {
    if (!name)
        return false;
    const brandName = getProviderBrandName(provider);
    // Check if it matches exactly (e.g., "ChatGPT")
    if (name === brandName)
        return true;
    // Check if it matches with number suffix (e.g., "ChatGPT_2", "Claude_3")
    const suffixPattern = new RegExp(`^${brandName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}_\\d+$`);
    return suffixPattern.test(name);
}
/**
 * Validate panelist name format
 * Names must not contain spaces to allow proper @mention tagging
 * Returns error message if invalid, null if valid
 */
export function validatePanelistName(name) {
    if (!name || !name.trim()) {
        return "Name cannot be empty";
    }
    if (name.includes(' ')) {
        return "Name cannot contain spaces (use underscores instead for @tagging)";
    }
    if (!/^[a-zA-Z0-9_-]+$/.test(name)) {
        return "Name can only contain letters, numbers, underscores, and hyphens";
    }
    if (name.length > 30) {
        return "Name must be 30 characters or less";
    }
    return null;
}
